const PrivacyPolicy = () => {
  return (
    <div className="p-20 select-none" onContextMenu={(e) => e.preventDefault()}>
        <h1 className="text-3xl uppercase text-white font-bold">
            Privacy Policy
        </h1>
        <p className="px-4"><br />
        This Privacy Policy, Terms and Conditions, and Cookies Policy 
        have been drafted in accordance with the laws of India, specifically 
        with the provisions under Rule 3(1) and Rule 4 of the Information 
        Technology (Intermediaries Guidelines) Rules, 2011. As per the 
        Information Technology Act, 2000, and the relevant Rules thereunder, 
        this document constitutes an ‘electronic record’ as defined under 
        section 2(t) of the Information Technology Act, 2000. <br /><br />
Being an electronic record, this document is generated by a computer 
system and does not require any physical or digital signatures to be 
valid. The provisions of these Terms and Policies are created in 
compliance with the applicable rules to regulate the use of the Internet 
of Things and ensure the protection of user data, security, and 
compliance with relevant legal standards. <br /><br />
This Privacy Policy outlines how TrialVest, owned by VKG Asset, manages 
and uses the personal data of users who interact with our platform. 
TrialVest is a litigation financing service, providing funds to 
claimants for pursuing their claims. <br /><br />
<b className="text-white">1. Ownership & Platform Details</b> TrialVest is operated by VKG Asset, a private limited firm with its registered office at <b className="text-white">D3/113, Sector 16, Rohini, New Delhi, India</b>. The platform, TrialVest, provides services to users who engage in litigation financing.
<br /><br /><b className="text-white">2. User Agreement</b> By accessing and using TrialVest’s platform (including the website, application, or linked services), you, the user (referred to as “You,” “User,” or “Client”), agree to be bound by this Privacy Policy. We recommend that you carefully read and understand this Policy before using or interacting with our platform.
<br /><br /><b className="text-white">3. Data Collection & Use</b> TrialVest collects personal information from users in order to facilitate litigation financing services. This data is used to provide and manage services, process transactions, communicate with users, and improve the platform.
<br /><br /><b className="text-white">4. User Rights</b> By agreeing to this Privacy Policy, you grant TrialVest the right to collect, store, and process personal information as necessary to deliver services. Users are advised not to use the platform if they do not agree with the terms of this policy.
<br /><br /><b className="text-white">Acceptance of Terms</b> By accessing, browsing, or using the TrialVest platform (the "Platform"), you, the User, acknowledge and agree to the terms and conditions set forth in this Privacy Policy. Your continued use of the Platform signifies your irrevocable acceptance and agreement to be bound by this Policy.
<br /><br />Before using the Platform, you must carefully read the Terms and Conditions. If you start using the Platform, we will presume that you have read and accepted the Terms and Conditions established by us. By simply using our Platform, you are entering into a contract with TrialVest, agreeing to comply with these terms and conditions, as well as the policies included within them.
<br /><br /><b className="text-white">5. Modifications to the Policy</b> TrialVest reserves the right to make any changes to this Privacy Policy at any time. We recommend that you periodically review the updated Policy. If you continue to use the Platform after any changes are made, it will be considered as your acceptance of such updates and modifications.
<br /><br /><b className="text-white">6. Refusal of Services</b> TrialVest reserves the right to deny access to any new users or terminate access for existing users at any time, without giving any reason, and without prior notice. If you fail to accept or comply with the terms of this Privacy Policy, TrialVest has the right to refuse service.
<br /><br /><b className="text-white">7. Privacy Policy and Terms</b> The Privacy Policy forms an integral part of the Terms and Conditions available on the TrialVest website. This policy, along with our terms of use, outlines how we collect, use, and disclose the information provided by our users. By using our platform, you consent to the practices described in this Privacy Policy.

<br /><br /><b className="text-white">Personal Information of Users</b><br /><br />
TrialVest collects personal information from users, including but not limited to: name, email address, residential address, phone number, photograph, and other details when users intend to use the platform. The primary purpose for collecting this information is to enhance user experience and provide new services, features, or improvements on the platform.
<br /><br />Users are free to decline providing personal information to TrialVest. However, if any user is using an account on behalf of a corporate entity, association, trust, or other organization, the user will be held responsible for the authorization of such use.
<br /><br />Additionally, TrialVest may receive and store technical information related to the user’s interaction with the platform, such as IP address, login ID, email address, password, device connection information, transaction history, and session data including the date, time, and duration of platform usage.
<br /><br />TrialVest also automatically collects certain information, including the URL of the website visited, the IP address of the user’s device, the type of web browser being used, email patterns, etc.

<br /><br /><b className="text-white">Cookie Policy</b><br /><br />
TrialVest uses cookies to improve user experience on its websites, including websites accessible through mobile applications. This Cookie Policy explains what cookies are and how we use them on our platforms.
<br /><br />If you do not wish to receive cookies while browsing our website, you can adjust your browser and/or mobile device settings to notify you when cookies are received, or you may choose to restrict or block cookies entirely.
<br /><br />Cookies are small files consisting of a string of letters and numbers placed on your computer or device by web page servers. They help us distinguish users from one another. Cookies cannot execute code, deliver viruses, or provide us access to your hard drive. Even if cookies are stored on your hard drive, we cannot read any other information stored there.
<br /><br />The data generated through cookies on TrialVest’s platforms may be used for the following purposes:
<br /><br /><b className="text-white">Strictly Necessary Cookies</b><br /><br />
These cookies are essential to enable you to move around the website and use its features, such as accessing secure areas or using platform search functions.
<br /><br /><b className="text-white">Performance Cookies</b><br /><br />
These cookies collect information about how visitors interact with the website, such as which pages are most visited and whether users encounter any errors. This data helps us improve the website in future versions.
<br /><br /><b className="text-white">Functionality Cookies</b><br /><br />
These cookies remember your preferences, such as your username, language, or region, to offer a more personalized experience.
<br /><br /><b className="text-white">Targeting or Advertising Cookies</b><br /><br />
These cookies are used to deliver content and advertisements that are more relevant to you based on your interests.
<br /><br />TrialVest does not permit third-party advertisers on its website, though we cannot control advertisements served by internet service providers while browsing the internet.
<br /><br />TrialVest is required by law to obtain user consent for all cookies, except those that are strictly necessary.
<br /><br />You can manage your cookies through your browser’s help function, device settings, or by following information on managing cookies available for popular browsers. Please note that some areas of the website may not function properly if cookies are disabled.

<br /><br /><b className="text-white">Use of Information of Users</b>
<br /><br />TrialVest collects personal and technical information from users when they interact with the platform. This information is primarily used to provide a customized and enhanced service experience. The details collected may also be used for the following purposes:
<br />•	Responding to user queries, requests, and inquiries.
<br />•	Updating users about new features and services on the platform.
<br />•	Improving, customizing, and enhancing platform services.
<br />•	Detecting and preventing fraud or misuse of the platform.
<br />•	Verifying the identity of users and administering the platform.
<br />•	Informing users of any changes in terms of use, policies, or services.
<br />•	Sending surveys, promotional materials, or marketing communications that may be of interest to users.
<br />•	Personalizing the user’s experience by presenting relevant advertising, products, or services.
<br />•	Resolving issues related to platform functionality, including technical problems.
<br />•	Processing payments and communicating regarding services or customer support.
<br />•	Protecting the integrity of the platform.
<br /><br />TrialVest may also use or share certain case-related information, as well as publicly available data for service enhancement.
<br /><br /><b className="text-white">Disclosure of User Information</b>
<br /><br />User information may be disclosed if required by law or when TrialVest believes such disclosure is necessary to respond to notices, court orders, or other legal processes.
<br /><br />Additionally, user information may be shared with law enforcement, third-party rights owners, or other parties when deemed necessary to enforce the platform’s terms, policies, or conditions of use. TrialVest does not sell user information but may share it as outlined in the terms and conditions and with user consent.
<br /><br />TrialVest may send promotional or offer-related communications directly to users. However, users have the option to unsubscribe from receiving such communications.
<br /><br />Information related to users' personal data may also be shared with the TrialVest team, data processors, and financing teams. When sharing personal data with third parties, TrialVest will take all reasonable steps to ensure the protection and proper handling of this information.

<br /><br /><b className="text-white">Security</b>
<br /><br />TrialVest is committed to safeguarding user information from unauthorized access and unethical usage. While the platform will take reasonable measures, including security reviews and the use of protective software, it is important to note that it is impossible to guarantee 100% security.
<br /><br />In case of unauthorized access, TrialVest will not be held liable for any data breach.

<br /><br /><b className="text-white">User Restrictions</b>
<br /><br />At the time of creating an account or accessing services on the platform, TrialVest will provide users with an identification code, password, or other security information. Users are responsible for maintaining the confidentiality of this information and should not disclose it to third parties.
<br /><br />To prevent unauthorized access, users should sign out from their account after use and refrain from sharing confidential information with others. TrialVest reserves the right to disable passwords or codes if users fail to comply with the platform’s terms or policies.
<br /><br />Users are solely responsible for activities under their account and should ensure their account credentials remain secure. TrialVest is not responsible for any unauthorized access arising from failure to maintain account confidentiality.

<br /><br /><b className="text-white">Third-Party Websites and Links</b>
<br /><br />TrialVest may link to third-party websites or advertisements. However, TrialVest is not responsible for the privacy practices or content of these external sites. Users should review the privacy policies of any third-party websites they visit.
<br /><br />TrialVest does not control cookies or other technologies used by advertisers on these external platforms. Any communication or data collection conducted by third parties is beyond TrialVest’s control.

<br /><br /><b className="text-white">General Terms</b>
<br /><br />The platform’s Privacy Policy is part of the overall Terms of Use and Terms and Conditions.
<br /><br />User information may remain in TrialVest's database even after users cease to use or access the platform. TrialVest is not liable for the usage of user information after such cessation.
<br /><br />User information may be stored or processed in any country, including those outside India, to enable the provision of services. TrialVest will ensure that data transfers comply with applicable Indian laws.
<br /><br />Users should be aware that their information could be accessed or used by third parties in cases where it is publicly available. TrialVest is not responsible for unsolicited communications received from third parties.
<br /><br />By using the platform, users agree that TrialVest has the right to use their posts, content, and personal data for the purpose of providing services. Users' public posts or reviews on the platform may be searchable on the internet, and TrialVest cannot guarantee that others will not copy or use the shared information.

<br /><br /><b className="text-white">Payment</b>
<br /><br />All payments made for services and investments on the TrialVest platform are directly processed by TrialVest. Users are advised to read the terms of use of the payment service providers before using their services. TrialVest will not be responsible or assume any liability for any loss or damage arising directly or indirectly from:
<br />•	Lack of authorization for any transactions.
<br />•	Any payment issues arising out of the transaction.
<br />•	Decline of a transaction for any reason.
<br /><br />All transaction prices, products, services, and commercial terms are governed by the contractual obligations between the users and the parties involved in the transaction.

<br /><br /><b className="text-white">Indemnity</b>
<br /><br />The user agrees to indemnify and hold harmless TrialVest, its executives, partners, shareholders, employees, agents, and affiliates from any and all liabilities, claims, losses, damages, or costs (including attorney fees) arising out of or in connection with:
<br />1.	Violation of applicable laws by the user.
<br />2.	Breach of any representations, warranties, or covenants made by the user.
<br />3.	Breach of any policies, guidelines, terms, conditions, or Privacy Policy of TrialVest (including any modifications or updates).
<br />4.	Infringement of third-party rights.
<br /><br />This indemnity clause will remain in effect even after the termination of this agreement.
<br /><br /><b className="text-white">Grievance Cell</b>
<br /><br />If you have any complaints or grievances, you can contact us at <u><a className="text-p3" href="mailto:care@trialvest.com">care@trialvest.com</a></u>.
<br /><br /><b className="text-white">Governing Law and Jurisdiction</b>
<br /><br />The terms and conditions of this policy shall be governed by Indian law. Any disputes arising from or related to this policy shall be resolved exclusively in the courts of Delhi, India.
<br /><br />
        </p>
    </div>
  )
}

export default PrivacyPolicy