const TermsConditions = () => {
  return (
    <div className="p-20 select-none" onContextMenu={(e) => e.preventDefault()}>
        
        <h1 className="text-3xl text-white font-bold">
        TERMS & CONDITIONS
        </h1>
        <p className="px-4"><br />
The law of land made provision to draft the Terms and Conditions, 
Privacy policy and Cookies policy to use an Internet of things. 
We, following the provisions of Rule 3(1) and 4 of the Information 
Technology (Intermediaries Guidelines) Rules, 2011, and are an 
‘electronic record’ as contemplated under section 2(t) of the 
Information Technology Act, 2000 and the Rules thereunder. These Terms 
being an electronic record are generated by a computer system and do not 
require any physical or digital signatures.<br/><br/>

The platform <i>TrialVest</i> has been introduced by VKG Asset, 
a Private Limited Firm, with its office located at D3/113, Sector 16, 
Rohini, New Delhi - 110085, India (hereinafter referred to as the 
“Owner,” “We,” “TrialVest,” or “Us”) to facilitate litigation financing 
services. Through TrialVest, we provide funds to claimants to support 
the progression of their litigation claims.<br/><br/>

<b className="text-white">Platform Use Terms</b><br/><br/>

The brand name <i>TrialVest</i> and the website 
 <a className="text-p3" href="www.trialvest.com"> <u>www.trialvest.com</u></a> are owned by 
VKG Asset Private Limited, with its office located at D3/113, Pocket 16, 
Rohini, New Delhi - 110085, India. All individuals who access or use the 
website, link, or platform are referred to as "Users" (hereinafter 
“You,” “User”).<br/><br/>
As a User, you are authorized to use the TrialVest platform in 
accordance with the terms and conditions outlined in this agreement. 
By accessing, browsing, or otherwise using the platform, you unequivocally 
and irrevocably accept and acknowledge these terms, conditions, and 
policies.<br/><br/>
Before using the platform, you must read and understand the terms and 
conditions set forth. By using our platform, we will assume you have 
reviewed these terms and consent to them. Your use of the platform 
constitutes a binding agreement with us, incorporating the terms, 
conditions, and policies.<br/><br/>
TrialVest reserves the right to grant or deny access to the platform at 
its discretion. We also retain the right to modify any of the terms and 
conditions at any time. It is your responsibility to periodically review 
any updates or changes. If you continue to use the platform after any 
updates, it will be considered as your acceptance of those changes.<br/><br/>
TrialVest also reserves the right to refuse access to new users or 
terminate access for existing users at any time, without providing 
any reason.<br/><br/>
All users of the TrialVest platform must comply with all applicable 
laws in India, including but not limited to the Information Technology 
Act, 2000, the Indian Contract Act, 1872, the Sale of Goods Act, 1930, 
along with any amendments, notifications, and rules related to these 
acts, as well as any other laws directly or indirectly applicable to the 
business conducted by TrialVest.<br/><br/>
<b className="text-white">USER ACCOUNT</b><br/><br/>
Creating an account on the TrialVest platform is free for users. 
However, TrialVest reserves the right to modify its fee policy at 
any time in the future. Any changes to the fee policy will be posted 
on the platform and will automatically become effective immediately 
thereafter. Unless otherwise specified, all fees will be quoted in 
Indian Rupees. Users can access and use the platform free of charge. 
However, TrialVest reserves the right to charge users for platform use 
in the future, provided that users are notified in advance of such 
charges.<br/><br/>
<b className="text-white">COMMUNICATIONS</b><br/><br/>
To use the TrialVest platform, users must provide a valid email address 
and/or phone number. If a user sends a message through WhatsApp, email, 
phone, SMS, or any other medium to the platform, it will be considered 
valid consent under the Indian Contract Act, allowing TrialVest to use 
the provided contact information for sending SMS notifications, updates, 
or any other communication related to our products, services, or platform 
updates.<br/><br/>
By signing into the platform, the user provides implied consent for 
TrialVest to use their data/information for communication purposes. 
The use of such data/information by TrialVest does not infringe on any 
legal or statutory rights of the user, as the user has consented to its 
use. Therefore, no claims can be made against TrialVest for using such 
data/information for the purposes outlined.<br/><br/>

<b className="text-white">SEVERABILITY</b><br/><br/>
Each provision of these terms is independent and distinct. If any 
provision becomes invalid, illegal, or unenforceable, the validity, 
legality, and enforceability of the remaining provisions will remain 
unaffected.<br/><br/>
<b className="text-white">FORCE MAJEURE</b><br/><br/>
Notwithstanding anything to the contrary in these terms, TrialVest shall 
not be held liable for any loss or damage caused by a Force Majeure Event. 
A "Force Majeure Event" includes, but is not limited to, events beyond 
TrialVest’s reasonable control such as fire, flood, explosion, acts of 
God, civil commotion, strikes, riots, insurrection, terrorist attacks, 
war, governmental actions, power failure, sabotage, unauthorized access 
to systems, viruses, hacking, bugs, or other similar events.<br/><br/>
<b className="text-white">DISPUTES</b><br/><br/>
Any complaints related to our services will be resolved amicably or 
through legal means. TrialVest is not responsible for resolving 
complaints related to market risks or any losses, as "investment is 
subject to market risk." TrialVest will not be liable, directly or 
indirectly, for any claims or proceedings made by users related to 
services offered through the platform.<br/><br/>
<b className="text-white">INTELLECTUAL PROPERTY RIGHTS</b><br/><br/>
All content on the TrialVest platform, including but not limited to 
text, graphics, logos, images, audio, data compilations, and software, 
is the property of TrialVest and is protected by intellectual property 
laws such as copyright, trademark, and patents. Users are prohibited 
from reproducing, distributing, or using any part of the platform’s 
content without prior written consent from TrialVest.<br/><br/>
The trademarks, logos, and service marks on the platform are owned by 
TrialVest or its affiliates, and users may not use these marks without 
express permission and in accordance with the terms and conditions 
established by TrialVest or the actual intellectual property owner.<br/><br/>
TrialVest owns all content related to copyrights, patents, trademarks, 
databases, source code, graphics, text, content, and other intellectual 
property. Users may not use, copy, modify, distribute, perform, or 
otherwise exploit this content without authorization.<br/><br/>
If users infringe upon intellectual property rights by using images, 
graphics, logos, or designs they do not own, they will be solely 
responsible for any resulting loss or damage to the rightful owner. 
TrialVest will not be held liable for such actions and does not support 
any activity that violates the legal rights of others.<br/><br/>
<b className="text-white">DISCLAIMER</b><br/><br/>
By using the TrialVest platform, you, the user, expressly agree that 
your use of the platform is at your own risk. All content provided by 
users, whether uploaded, shared, or otherwise made available on the 
platform, is provided "as is" without any changes, modifications, or 
warranties, whether express, implied, statutory, or otherwise. This 
includes, but is not limited to, implied warranties of title, 
non-infringement, suitability, accuracy, reliability, completeness, 
timeliness, performance, safety, merchantability, fitness for a particular 
purpose, or the legality of the products listed or displayed. TrialVest 
does not accept liability for any errors or omissions to the extent 
permitted by applicable Indian law.<br/><br/>
<b className="text-white">LIMITATION OF LIABILITY</b><br/><br/>
TrialVest, its executives, partners, employees, and associates shall not 
be held liable for any loss or damage, including but not limited to direct, 
indirect, punitive, incidental, and consequential damages, loss of profits, 
or damages resulting from your use or inability to use the platform.<br/><br/>
<b className="text-white">INDEMNITY</b><br/><br/>
You agree to indemnify and hold harmless TrialVest, its executives, 
partners, shareholders, and employees from any harm or claims. You 
further agree to indemnify TrialVest from all actions, proceedings, 
claims, losses, damages, costs (including attorney fees), and expenses 
suffered or incurred as a result of (i) violation of any applicable law, 
(ii) breach of any representations or agreements by you, (iii) breach of 
the platform’s policies, guidelines, or terms, (iv) infringement of any 
third-party rights. This indemnity clause remains in effect even after 
the termination of this agreement.<br/><br/>
<b className="text-white">VIOLATION OF THESE TERMS OF USE</b><br/><br/>
TrialVest may disclose any information about you, including your 
identity, if necessary for an investigation or complaint regarding your 
use of the platform, or to identify, contact, or take legal action 
against someone causing harm or interference with the platform, either 
intentionally or unintentionally.<br/><br/>
You agree that TrialVest may preserve communications or data you 
transmit through the platform and disclose such information if required 
by law or if necessary to (1) comply with legal processes, (2) enforce 
these Terms of Use, (3) address claims of data violations, or (4) 
protect the rights, property, or safety of TrialVest, its users, or 
the public.<br/><br/>
You acknowledge that any violation of these Terms of Use may result in 
termination of your access to the platform and blocking of future access. 
You further agree that such violations may cause irreparable harm to 
TrialVest, for which monetary damages would be insufficient. You consent 
to TrialVest seeking injunctive or equitable relief if necessary.<br/><br/>
TrialVest may, at its sole discretion and without prior notice, terminate 
your access to the platform for causes including (1) requests from law 
enforcement or government agencies, (2) your self-initiated account 
deletion, (3) discontinuance or modification of platform services, or 
(4) unexpected technical issues.<br/><br/>
<b className="text-white">TERMINATION</b><br/><br/>
TrialVest reserves the right to terminate the services provided on the 
platform to any user without prior notice in the event of any default 
committed by the user, including but not limited to breaches of applicable 
laws, policies, guidelines, or any terms and conditions set by TrialVest. 
The owner may also terminate the user’s account if the user is deemed 
non-valuable to the business.<br/><br/>
Upon termination of the account, TrialVest retains the right to store 
and use any data or information previously stored on the platform’s 
servers.<br/><br/>
If TrialVest takes legal action against you due to your violation of 
these Terms of Use, TrialVest is entitled to recover any losses from 
you. You agree to pay all reasonable costs arising from such actions, 
including any other relief granted to TrialVest. TrialVest will not be 
liable to you or any third party for termination of your access to the 
platform due to any violation of these Terms of Use.<br/><br/>
<b className="text-white">COVENANTS</b><br/><br/>
<b className="text-white">a. Use of the Platform:</b><br />
All users of the platform agree to abide by additional terms, rules, 
policies, procedures, guidelines, disclaimers, or notices. If there’s a 
conflict between previous terms and additional terms, the additional 
terms shall prevail. You agree to use the platform and materials 
provided on it only for purposes allowed by these terms and applicable 
law, and in a manner that does not harm TrialVest or its affiliates. <br /><br />
<b className="text-white">b. Content on the Platform:</b><br />
You agree that any reviews, comments, or other information posted on the platform are not false, misleading, or fraudulent. <br /><br />
<b className="text-white">c. Objectionable Content:</b><br />
You agree not to host, display, upload, modify, transmit, update, or share content that: <br />
i. Belongs to another person and you do not have rights to it;<br />
ii. Is harmful, harassing, defamatory, obscene, pornographic, invasive 
of privacy, hateful, or objectionable;<br />
iii. Relates to money laundering, gambling, or is otherwise unlawful;<br />
iv. Harms minors in any way;<br />
v. Exploits people or contains unlawful material;<br />
vi. Infringes on intellectual property rights;<br />
vii. Violates any law;<br />
viii. Is misleading or offensive in nature;<br />
ix. Impersonates another person;<br />
x. Attempts unauthorized access;<br />
xi. Contains viruses or harmful software;<br />
xii. Threatens national security or public order;<br />
xiii. Creates liability for TrialVest or its affiliates. <br /><br />
<b className="text-white">Liability of Objectionable Content:</b><br />
TrialVest disclaims any liability arising from objectionable content on 
the platform. If a user encounters such content, they are encouraged to 
immediately report it to the grievance cell. TrialVest will make 
reasonable efforts to remove such content after investigation. <br /><br />

<b className="text-white">USE OF CONTENT</b><br /><br />
By posting any material or information on the platform, the user grants 
<b className="text-white"> TrialVest</b> and its affiliates a non-exclusive, royalty-free, 
irrevocable, perpetual, and fully sub-licensable right to use, 
reproduce, publish, distribute, and display such content worldwide, in 
any medium or manner now known or developed in the future. This includes 
the right to use the user's name in connection with the content. <br /><br />
The user agrees that these rights are irrevocable throughout the protection 
period of their intellectual property rights. The user also waives the 
right to be identified as the author of the content and to object to 
any derogatory treatment of it. The user agrees to perform all necessary 
actions to perfect these rights granted to <b className="text-white">TrialVest</b>. <br /><br />
The user represents and warrants that they own or control all the rights to the content they post or provide on the platform, and that the content is accurate, does not violate any applicable laws, and does not breach the platform’s terms or privacy policy.
<br /><br /><b className="text-white">THIRD-PARTY WEBSITES</b><br /><br />
<b className="text-white">TrialVest</b> may link to third-party websites or applications. 
The owner of the platform is not responsible for the terms of use or 
content of these linked websites, and expressly disclaims all liability 
related to their use. The linked websites are not under <b className="text-white">TrialVest's </b> 
control, and users should review their terms and privacy policies 
before accessing them. <br /><br />
There may be risks associated with accessing third-party websites, and 
<b className="text-white"> TrialVest</b> will not be responsible for any consequences arising 
from such access. <br /><br />
Users are not authorized to use any technology or methods to copy or 
recreate content, images, documents, or information from the platform.

<br /><br /><b className="text-white">USE OF PLATFORM</b><br /><br />
Users agree not to interfere with the smooth functioning of the platform, modify security features, or create any derivative works from the platform’s source code without written permission from <b className="text-white">TrialVest</b>. <br /><br />
By using the platform, users explicitly consent to receive communications from <b className="text-white">TrialVest</b> regarding their use of the platform and services. These communications are not considered unsolicited.

<br /><br /><b className="text-white">MISCELLANEOUS</b><br /><br />
<b className="text-white">TrialVest</b> is a facilitator displaying funding activities and providing related services. The platform may require the use of various tools and devices, and <b className="text-white">TrialVest</b> is not responsible for any issues that occur while using it, including hacker attacks or technical problems.
<br /><br /><b className="text-white">TrialVest</b> will not be liable for damages, viruses, or other issues affecting users’ systems or devices while using the platform. The platform may not be compatible with all hardware and software, and <b className="text-white">TrialVest</b> makes no warranty regarding compatibility.

<br /><br /><b className="text-white">SEVERABILITY</b><br /><br />
Each provision in these terms is severable. If any provision is invalid or unenforceable, the remaining provisions will continue to be enforceable. In the case of any invalid provision, <b className="text-white">TrialVest</b> may replace it with a valid and enforceable provision.

<br /><br /><b className="text-white">NOTICES</b><br /><br />
<b className="text-white">TrialVest</b> may notify users about changes to these terms through a banner notice on the platform or via email. Users agree to keep their contact details up to date to receive service messages and notifications.

<br /><br /><b className="text-white">ASSIGNMENT</b><br /><br />
Users may not assign their rights or obligations under these terms to third parties. <b className="text-white">TrialVest</b> may assign its rights to affiliates or partners without user consent.

<br /><br />This language ensures clarity regarding content ownership, platform use, third-party links, and platform-related issues. It establishes necessary terms for operating the platform while protecting <b className="text-white">TrialVest</b> and ensuring user compliance.

        </p>
    </div>
  )
}

export default TermsConditions